name: Test Pipeline

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, stage]
  workflow_dispatch:

jobs:
  # typo-check:
  #   uses: ./.github/workflows/_typo-check.yml

  tests-services:
    uses: ./.github/workflows/_tests-services.yml

  validate-resources:
    uses: ./.github/workflows/_validate-resources.yml
