name: Resources Checking

on:
  push:
    branches: [main, stage, dev]
    paths:
      - "resources/**"
  pull_request:
    branches: [main, stage]
    paths:
      - "resources/**"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dir:
          - resources/admin
          - resources/backend
          - resources/observability
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"
      - name: Terraform fmt
        run: terraform fmt -check
        working-directory: ${{ matrix.dir }}
      - name: Terraform init
        run: terraform init -backend=false
        working-directory: ${{ matrix.dir }}
      - name: Terraform validate
        run: terraform validate -no-color
        working-directory: ${{ matrix.dir }}
